# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-03 10:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0004_hotsearchwords_indexad'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='', max_length=100, verbose_name='\u7701\u4efd')),
                ('city', models.CharField(default='', max_length=100, verbose_name='\u57ce\u5e02')),
                ('district', models.CharField(default='', max_length=100, verbose_name='\u533a\u57df')),
                ('address', models.CharField(default='', max_length=100, verbose_name='\u8be6\u7ec6\u5730\u5740')),
                ('signer_name', models.CharField(default='', max_length=100, verbose_name='\u7b7e\u6536\u4eba')),
                ('signer_mobile', models.CharField(default='', max_length=11, verbose_name='\u7535\u8bdd')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u6536\u8d27\u5730\u5740',
                'verbose_name_plural': '\u6536\u8d27\u5730\u5740',
            },
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.IntegerField(default=0, verbose_name='\u8d2d\u4e70\u6570\u91cf')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='\u5546\u54c1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6536\u85cf',
                'verbose_name_plural': '\u7528\u6237\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='UserLeavingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.IntegerField(choices=[(1, '\u7559\u8a00'), (2, '\u6295\u8bc9'), (3, '\u8be2\u95ee'), (4, '\u552e\u540e'), (5, '\u6c42\u8d2d')], default=1, help_text='\u7559\u8a00\u7c7b\u578b: 1(\u7559\u8a00),2(\u6295\u8bc9),3(\u8be2\u95ee),4(\u552e\u540e),5(\u6c42\u8d2d)', verbose_name='\u7559\u8a00\u7c7b\u578b')),
                ('subject', models.CharField(default='', max_length=100, verbose_name='\u4e3b\u9898')),
                ('message', models.TextField(default='', help_text='\u7559\u8a00\u5185\u5bb9', verbose_name='\u7559\u8a00\u5185\u5bb9')),
                ('file', models.FileField(help_text='\u4e0a\u4f20\u7684\u6587\u4ef6', upload_to='message/images/', verbose_name='\u4e0a\u4f20\u7684\u6587\u4ef6')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7559\u8a00',
                'verbose_name_plural': '\u7528\u6237\u7559\u8a00',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set([('user', 'goods')]),
        ),
    ]
