# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20180207_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAddres',
            new_name='UserAddress',
        ),
    ]
