# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 15:27
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_decs',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u5185\u5bb9'),
        ),
        migrations.AddField(
            model_name='goods',
            name='sold_num',
            field=models.IntegerField(default=0, verbose_name='\u5546\u54c1\u9500\u552e\u91cf'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_num',
            field=models.IntegerField(default=0, verbose_name='\u5e93\u5b58\u6570'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='market_price',
            field=models.FloatField(default=0, verbose_name='\u5e02\u573a\u4ef7\u683c'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u5546\u54c1\u540d'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='shop_price',
            field=models.FloatField(default=0, verbose_name='\u672c\u5e97\u4ef7\u683c'),
        ),
    ]
