# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180208_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='\u7236\u76ee\u5f55', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.GoodsCategory', verbose_name='\u7236\u7c7b\u76ee\u7ea7\u522b'),
        ),
    ]
