# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-03 08:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180219_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotSearchWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='', max_length=20, verbose_name='\u70ed\u641c\u8bcd')),
                ('index', models.IntegerField(default=0, verbose_name='\u6392\u5e8f')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u70ed\u641c\u8bcd',
                'verbose_name_plural': '\u70ed\u641c\u8bcd',
            },
        ),
        migrations.CreateModel(
            name='IndexAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='goods.GoodsCategory', verbose_name='\u5546\u54c1\u7c7b\u76ee')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.Goods')),
            ],
            options={
                'verbose_name': '\u9996\u9875\u5546\u54c1\u7c7b\u522b\u5e7f\u544a',
                'verbose_name_plural': '\u9996\u9875\u5546\u54c1\u7c7b\u522b\u5e7f\u544a',
            },
        ),
    ]
