# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180224_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('female', '\u5973'), ('male', '\u7537')], default='female', max_length=6, verbose_name='\u6027\u522b'),
        ),
    ]
