# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180225_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u90ae\u4ef6'),
        ),
    ]
